### ISSUE TITLE
How to use it only by python

### ISSUE THREAD

**Issue by ds1231h** [idealo/image-quality-assessment#2]
Could you please tell me how to use it only by python? Both create my own model or use your model are both ok for me.
Because I can just use python on my computer, I wish you could give me some advice.

**Comment by clennan** [comment]
In order to train and predict without Docker containers (not recommended) you need to install the Python requirements

`pip install -r src/requirements.txt`

and then follow the entrypoint scripts

[entrypoint.train.cpu.sh](https://github.com/idealo/image-quality-assessment/blob/master/entrypoints/entrypoint.train.cpu.sh)
[entrypoint.predict.cpu.sh](https://github.com/idealo/image-quality-assessment/blob/master/entrypoints/entrypoint.predict.cpu.sh)

Hope that helps :)

**Comment by Edwardmark** [comment]
@clennan I run the following command in src as working directory:   
python -m evaluater.predict --base-model-name MobileNet --weights-file ../models/MobileNet/weights_mobilenet_technical_0.11.hdf5 --image-source ./new/test_images/

But I get the error :
/usr/bin/python: No module named evaluater

How to run it with pure python?
Thanks, man.

**Comment by FantasyJXF** [comment]
@Edwardmark 

add the following lines before `import utils....` in `predict.py` would solve your problem
```
import sys
sys.path.append(os.getcwd())
```
