### ISSUE TITLE
Retraining on specific dataset to improve predictions

### ISSUE THREAD

**Issue by ThiesDS** [idealo/image-quality-assessment#28]
Hey, 

you retrained the NIMA model on your own hotel images and obtained a significant increase in accuracy in aesthetic and technical quality predictions, right? We are about to adapt this approach and would like to refine your model on our specific dataset (and then make it available to the community again). Currently we try to figure out the setup for labeling the images. What is your experience on how many images need to be labled to effectively train the CNNs? And did you use a specific software to do so? 

Best
Sven

**Comment by clennan** [comment]
Hi Sven, yes, especially the aesthetic model improved by training it on a hotel dataset. I would say labelling around 2k hotel images on aesthetics, where each image has around 8 scores, should be sufficient, so a total of 16k human scores.  We ended up labelling more images, but the gains in performance were marginal. We built our own labelling application and used in-house people for labelling. Mechanical Turk might be a good alternative here.

For the technical classifier the in-house labelling did not work well, we switched to generating synthetic labels and improved the model, but still not sufficiently good for putting it in production. The problem here is that technical quality is not domain specific, so you can't make the classification problem easier by restricting it to a hotel domain for example, and that ImageNet CNNs are probably a bad choice in the first place for technical quality.

**Comment by clennan** [comment]
And cool that you are planning to open source them! We could add the models to this repository if you wish ;)

**Comment by ThiesDS** [comment]
Thanks very much for these informations! Big fan of open sourcing knowledge. However, that might take some more time to get there, but definitely the goal. Looking forward to it. :-)

**Comment by clennan** [comment]
Cool, let us know if you need further infos. I will close this issue for now, feel free to reopen if you have updates/questions.
